### ISSUE TITLE
Idea: Replicating the &MULT with the Array Modifier

### ISSUE THREAD

**Issue by TristanHehnen** [firetools/blenderfds#16]
Dear Emanuele,

it seems that the behaviour of &MULT could be replicated/translated to the Array Modifier and back. The I/J/K_UPPER could then be three arrays in the different axis. Maybe this could be an interesting convenience function, at least for importing FDS input files into Blender. In the import menu could be a checkmark that allows the user to control the behaviour.

Best,
Tristan

**Comment by emanuelegissi** [comment]
Great idea Tristan.
I have been using the MULT line in qgis2fds since yesterday, following your
peek.
Let's what can be done in BlenderFDS

Il giorno gio 19 ago 2021 alle ore 11:08 FireTristan <
***@***.***> ha scritto:

**Comment by emanuelegissi** [comment]
I have implemented the MULT functionality, both importing and exporting.

If you want to test the new BlenderFDS version that works very well with [Blender 3.2 beta](https://builder.blender.org/download/daily/), try the [blender32 branch of this repo](https://github.com/firetools/blenderfds/tree/blender32).

I had to skip Blender 3.1 because it had a bug that prevented geometry export.

**Comment by TristanHehnen** [comment]
Thank you very much! 
Right now I'm experiencing an issue with importing FDS files in Blender 3.2 beta.

"Import: Unresolved relative path, save the Blender file", see issue #21

**Comment by emanuelegissi** [comment]
It is done. I wait for your confirmation to close this issue. Thank you

**Comment by TristanHehnen** [comment]
When importing a file with the `&MULT`, for example `PMMA_60_kW.fds` from the validation suite. The `I_UPPER` etc. are filled in as expected. 
I was hoping it would also "add in" the instances, like when using the Array modifier, as a visualisation of the overall structure.

When using the FDS MULT in the Object Properties panel the exported input lines in the FDS file are then multiple instances of the `MESH` definitions according to the number of instances, but not the input lines of the `MULT` namelist - which is fine since the result is effectively the same, just unexpected.

It also seems that there is a split defined in the startup file, a 3 the z-axis. I'm not sure if this intentional or not.
![grafik](https://user-images.githubusercontent.com/34650649/170115514-633ec287-8848-462d-8ccd-b631dd44f5cf.png)

**Comment by emanuelegissi** [comment]
On Tue, May 24, 2022, 21:21 FireTristan ***@***.***> wrote:

> When importing a file with the &MULT, for example PMMA_60_kW.fds from the
> validation suite. The I_UPPER etc. are filled in as expected.
> I was hoping it would also "add in" the instances, like when using the
> Array modifier, as a visualisation of the overall structure.
>
If you click on "Show geometry" it should show all the instances. And you
can leave them visible if you want.

I tried to use the array modifier, but it was not compatible with the MULT
logic. So I decided to keep the MULT as it is in FDS. I imagine the users
knowing better the FDS side than the Blender one...

When using the FDS MULT in the Object Properties panel the exported input
> lines in the FDS file are then multiple instances of the MESH definitions
> according to the number of instances, but not the input lines of the MULT
> namelist - which is fine since the result is effectively the same, just
> unexpected.
>
In the first version of the feature you could decide to export the MULT.

Then when I developed the MPI_PROCESS automatic assignment, I preferred to
have the multiple instances. Otherwise you cannot assign the process.

Do you think we could inform the user better about that?

It also seems that there is a split defined in the startup file, a 3 the
> z-axis. I'm not sure if this intentional or not.[image: grafik]
> <https://user-images.githubusercontent.com/34650649/170115514-633ec287-8848-462d-8ccd-b631dd44f5cf.png>
>
It is not intentional, it is a bug ;-)
I am going to fix that.

Speaking about the documentation. I am very interested in your point of
view.
What additional pages should be added to the wiki?

In the next days, I am going to write something on the Domain (split, MULT
and MPI_PROCESS) and run FDS/smokeview.

Have you tested the "run FDS" feature? Does it work in your windows
computer? I didn't test it much.

Ema

<https://user-images.githubusercontent.com/34650649/170115514-633ec287-8848-462d-8ccd-b631dd44f5cf.png>

**Comment by TristanHehnen** [comment]
MULT / array modifier:
Thank you for the clarification, somehow I forgot to click the "show geometry" button. I'm not sure how the user could be better informed in Blender itself about the MPI_PROCESS aspect. Maybe there could be a short sentence in the object properties tab of the MESH in the FDS MULT section. Similar to the text for the cell size. It could also point to the wiki and then there is a more detailed description.


Documentation:
Right now I don't have had the time to read the new wiki carefully, thus I have no suggestions here. I'll let you know when I read it fully.

Run FDS:
I didn't test this functionality on windows yet. Typically in my workflow I have other scripts that I use to control the simulations on the cluster and rarely run FDS from within software like Blender or Pyrosim (I believe they have similar functionality).

Thanks,
Tristan
