### ISSUE TITLE
Update for Blender 3.0.1

### ISSUE THREAD

**Issue by uporersith** [firetools/blenderfds#20]
THe new update to Blender 3.0.1 breaks blenderFDS. I looked through the changelog and found the culprit. 

IN geometry/utils.py on line 35, remove the deprecated argument "Deform=True" from bm.from_object()

- Remove unused BMesh.from_object deform argument ([ead084b6e1](https://developer.blender.org/rBead084b6e1a05b9bff943660ea104efbed9b845f)).
([https://wiki.blender.org/wiki/Reference/Release_Notes/3.0/Python_API](https://wiki.blender.org/wiki/Reference/Release_Notes/3.0/Python_API))

and it works again. 

Hope this helps.

**Comment by emanuelegissi** [comment]
Great, thank you.

I'm working very hard to the new release of BlenderFDS that will have full
compatibility with blender 3, lots of new features, and hopefully largely
improved dependability.

**Comment by emanuelegissi** [comment]
If you want to test the new BlenderFDS version that works very well with [Blender 3.2 beta](https://builder.blender.org/download/daily/), try the [blender32 branch of this repo](https://github.com/firetools/blenderfds/tree/blender32).
I had to skip Blender 3.1 because it had a bug that prevented geometry export.

I am getting close to the release.

**Comment by emanuelegissi** [comment]
The new BlenderFDS is now feature complete. I am now starting to update the documentation.

The branches have been merged back to master.
If you want to test it, please install h [Blender 3.2 beta](https://builder.blender.org/download/daily/) and download the [master branch](https://github.com/firetools/blenderfds/archive/refs/heads/master.zip) of this repo.
